using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using FartSymphony.Core;
using FartSymphony.Gameplay;
using FartSymphony.UI;

namespace FartSymphony.Editor
{
    /// <summary>
    /// Builds the Sprint 2 development scene with all systems and art assets wired.
    /// Menu: FartSymphony → Build Sprint2Dev Scene
    /// </summary>
    public static class Sprint2SceneBuilder
    {
        // ── Asset paths ────────────────────────────────────────────────────────
        // Production art (Unicode escapes — avoid source-file encoding issues)
        private const string PATH_BG          = "Assets/art/\u6F14\u594F\u72B6\u6001\u5E95\u56FE.png";
        private const string PATH_TRACK       = "Assets/art/UI/\u97F3\u7B26\u8F68\u9053.png";
        private const string PATH_JUDGE_POINT = "Assets/art/UI/\u97F3\u7B26\u8F68\u9053\u5224\u5B9A\u70B9.png";
        private const string PATH_NOTE_NORMAL = "Assets/art/\u6F14\u594F\u666E\u901A\u97F3\u7B26\u6548\u679C\u56FE.png";
        private const string PATH_BLOAT_BG    = "Assets/art/UI/\u5C41\u503C\u6761\u5E95\u56FE.png";
        private const string PATH_BLOAT_FILL  = "Assets/art/UI/\u5C41\u503C\u6761\u80FD\u91CF.png";
        private const string PATH_BLOAT_TOP   = "Assets/art/UI/\u5C41\u503C\u6761\u9876\u56FE.png";

        // Placeholder art (generated by PlaceholderAssetGenerator)
        private const string PH_BG          = "Assets/art/placeholders/bg.png";
        private const string PH_TRACK       = "Assets/art/placeholders/note_track.png";
        private const string PH_JUDGE_POINT = "Assets/art/placeholders/judgment_line.png";
        private const string PH_NOTE        = "Assets/art/placeholders/note_icon.png";
        private const string PH_BLOAT_BG    = "Assets/art/placeholders/bloat_bg.png";
        private const string PH_BLOAT_FILL  = "Assets/art/placeholders/bloat_fill.png";
        private const string PH_BLOAT_TOP   = "Assets/art/placeholders/bloat_top.png";

        [MenuItem("FartSymphony/Build Sprint2Dev Scene")]
        public static void Build() => BuildInternal();

        /// <summary>Called by PlaceholderAssetGenerator after generating placeholder PNGs.</summary>
        public static void BuildWithPlaceholders() => BuildInternal();

        /// <summary>
        /// Resolves each asset: tries production path first, falls back to placeholder.
        /// </summary>
        private static void BuildInternal()
        {
            string pBg    = Pick(PATH_BG,          PH_BG);
            string pTrack = Pick(PATH_TRACK,        PH_TRACK);
            string pJudge = Pick(PATH_JUDGE_POINT,  PH_JUDGE_POINT);
            string pNote  = Pick(PATH_NOTE_NORMAL,  PH_NOTE);
            string pBBg   = Pick(PATH_BLOAT_BG,     PH_BLOAT_BG);
            string pBFill = Pick(PATH_BLOAT_FILL,   PH_BLOAT_FILL);
            string pBTop  = Pick(PATH_BLOAT_TOP,    PH_BLOAT_TOP);

            // 1. Ensure Sprite import mode
            SetSprite(pBg); SetSprite(pTrack); SetSprite(pJudge); SetSprite(pNote);
            SetSprite(pBBg); SetSprite(pBFill); SetSprite(pBTop);
            AssetDatabase.Refresh();
            AssetDatabase.SaveAssets();

            // 2. Load sprites
            var bgSprite        = LoadSprite(pBg);
            var trackSprite     = LoadSprite(pTrack);
            var judgePtSprite   = LoadSprite(pJudge);
            var noteSprite      = LoadSprite(pNote);
            var bloatBgSprite   = LoadSprite(pBBg);
            var bloatFillSprite = LoadSprite(pBFill);
            var bloatTopSprite  = LoadSprite(pBTop);

            // 3. Create fresh scene
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // ── Camera ───────────────────────────────────────────────────────
            var camGo = new GameObject("Main Camera");
            var cam   = camGo.AddComponent<Camera>();
            cam.tag            = "MainCamera";
            cam.backgroundColor= Color.black;
            cam.clearFlags     = CameraClearFlags.SolidColor;
            cam.orthographic   = true;
            camGo.AddComponent<AudioListener>();

            // ── Directional Light ────────────────────────────────────────────
            var lightGo = new GameObject("Directional Light");
            lightGo.transform.rotation = Quaternion.Euler(50f, -30f, 0f);
            var dl = lightGo.AddComponent<Light>();
            dl.type  = LightType.Directional;
            dl.color = Color.white;

            // ── Canvas ───────────────────────────────────────────────────────
            var canvasGo = new GameObject("Canvas");
            var canvas   = canvasGo.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            var scaler = canvasGo.AddComponent<CanvasScaler>();
            scaler.uiScaleMode        = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920f, 1080f);
            scaler.screenMatchMode    = CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;
            scaler.matchWidthOrHeight  = 0.5f;
            canvasGo.AddComponent<GraphicRaycaster>();

            // Background (fill entire canvas)
            var bgGo  = CreateImage(canvasGo.transform, "Background", bgSprite);
            FillParent(bgGo.GetComponent<RectTransform>());

            // Vignette overlay (semi-transparent black, starts at alpha=0)
            var vigGo  = CreateImage(canvasGo.transform, "Vignette", null);
            var vigImg = vigGo.GetComponent<Image>();
            vigImg.color = new Color(0f, 0f, 0f, 0f);
            FillParent(vigGo.GetComponent<RectTransform>());

            // Note Track (horizontal bar, center of screen)
            var trackGo   = CreateImage(canvasGo.transform, "NoteTrack", trackSprite);
            var trackRect = trackGo.GetComponent<RectTransform>();
            trackRect.anchorMin = new Vector2(0f, 0.44f);
            trackRect.anchorMax = new Vector2(1f, 0.56f);
            trackRect.offsetMin = Vector2.zero;
            trackRect.offsetMax = Vector2.zero;
            trackGo.GetComponent<Image>().type = Image.Type.Tiled;

            // Judgment line — bright yellow solid bar, 12px wide, extends above/below track
            var judgeGo   = new GameObject("JudgmentLine");
            judgeGo.transform.SetParent(trackGo.transform, false);
            var judgeImg  = judgeGo.AddComponent<Image>();
            judgeImg.color = new Color(1f, 0.92f, 0.1f, 1f);   // bright yellow
            var judgeRect = judgeGo.GetComponent<RectTransform>();
            judgeRect.anchorMin        = new Vector2(0.15f, -0.5f);
            judgeRect.anchorMax        = new Vector2(0.15f,  1.5f);
            judgeRect.pivot            = new Vector2(0.5f,   0.5f);
            judgeRect.sizeDelta        = new Vector2(12f,    0f);
            judgeRect.anchoredPosition = Vector2.zero;

            // Note prefab (hidden — pool source for VisualCueSystem)
            // Plain white rect, no sprite — VisualCueSystem tints by intensity (Sprint 1 style)
            var notePrefabGo   = new GameObject("NotePrefab");
            notePrefabGo.transform.SetParent(trackGo.transform, false);
            var notePrefabImg  = notePrefabGo.AddComponent<Image>();
            notePrefabImg.color  = Color.white;
            notePrefabImg.sprite = null;
            var notePrefabRect = notePrefabGo.GetComponent<RectTransform>();
            notePrefabRect.anchorMin        = new Vector2(0f, 0.1f);
            notePrefabRect.anchorMax        = new Vector2(0f, 0.9f);
            notePrefabRect.pivot            = new Vector2(0.5f, 0.5f);
            notePrefabRect.sizeDelta        = new Vector2(10f, 0f);   // thin vertical bar like S1
            notePrefabRect.anchoredPosition = Vector2.zero;
            notePrefabGo.SetActive(false);

            // ── Bloat Gauge (right side, vertical fill) ──────────────────────
            // Container: right 7% of screen, 80% height
            var bloatContGo   = new GameObject("BloatGaugeContainer");
            bloatContGo.transform.SetParent(canvasGo.transform, false);
            var bloatContRect = bloatContGo.AddComponent<RectTransform>();
            bloatContRect.anchorMin = new Vector2(0.91f, 0.10f);
            bloatContRect.anchorMax = new Vector2(0.98f, 0.90f);
            bloatContRect.offsetMin = Vector2.zero;
            bloatContRect.offsetMax = Vector2.zero;

            // Background frame
            var bloatBgGo = CreateImage(bloatContGo.transform, "BloatBackground", bloatBgSprite);
            FillParent(bloatBgGo.GetComponent<RectTransform>());

            // Fill (grows upward, tinted green→red by code)
            var bloatFillGo  = CreateImage(bloatContGo.transform, "BloatFill", bloatFillSprite);
            var bloatFillImg = bloatFillGo.GetComponent<Image>();
            bloatFillImg.type       = Image.Type.Filled;
            bloatFillImg.fillMethod = Image.FillMethod.Vertical;
            bloatFillImg.fillOrigin = (int)Image.OriginVertical.Bottom;
            bloatFillImg.fillAmount = 0.3f;   // visible test value
            bloatFillImg.color      = new Color(0.2f, 0.8f, 0.2f, 1f);
            var bloatFillRect = bloatFillGo.GetComponent<RectTransform>();
            bloatFillRect.anchorMin = Vector2.zero;
            bloatFillRect.anchorMax = Vector2.one;
            bloatFillRect.offsetMin = new Vector2(4f,  4f);
            bloatFillRect.offsetMax = new Vector2(-4f, -4f);

            // Top cap — anchored to TOP of container, fixed height
            var bloatTopGo   = CreateImage(bloatContGo.transform, "BloatTop", bloatTopSprite);
            var bloatTopRect = bloatTopGo.GetComponent<RectTransform>();
            bloatTopRect.anchorMin = new Vector2(0f, 1f);
            bloatTopRect.anchorMax = new Vector2(1f, 1f);
            bloatTopRect.pivot     = new Vector2(0.5f, 1f);
            bloatTopRect.sizeDelta = new Vector2(0f, 20f);

            // ── Suspicion Meter (left side, vertical fill) ───────────────────
            var suspContGo   = new GameObject("SuspicionMeterContainer");
            suspContGo.transform.SetParent(canvasGo.transform, false);
            var suspContRect = suspContGo.AddComponent<RectTransform>();
            suspContRect.anchorMin = new Vector2(0.02f, 0.10f);
            suspContRect.anchorMax = new Vector2(0.09f, 0.90f);
            suspContRect.offsetMin = Vector2.zero;
            suspContRect.offsetMax = Vector2.zero;

            // Background (dark bordered rect using placeholder)
            var suspBgGo = CreateImage(suspContGo.transform, "SuspicionBackground", null);
            suspBgGo.GetComponent<Image>().color = new Color(0.05f, 0.05f, 0.1f, 0.85f);
            FillParent(suspBgGo.GetComponent<RectTransform>());

            // Label text at top
            var suspLabelGo   = new GameObject("SuspicionLabel");
            suspLabelGo.transform.SetParent(suspContGo.transform, false);
            var suspLabel     = suspLabelGo.AddComponent<Text>();
            suspLabel.text      = "Suspicion";
            suspLabel.fontSize  = 18;
            suspLabel.alignment = TextAnchor.UpperCenter;
            suspLabel.color     = new Color(0.9f, 0.7f, 0.3f, 1f);
            var suspLabelRect  = suspLabelGo.GetComponent<RectTransform>();
            suspLabelRect.anchorMin = new Vector2(0f, 0.88f);
            suspLabelRect.anchorMax = new Vector2(1f, 1f);
            suspLabelRect.offsetMin = Vector2.zero;
            suspLabelRect.offsetMax = Vector2.zero;

            // Fill bar
            var suspFillGo   = CreateImage(suspContGo.transform, "SuspicionFill", null);
            var suspFillImg  = suspFillGo.GetComponent<Image>();
            suspFillImg.color      = new Color(0.2f, 0.7f, 1f, 1f);
            suspFillImg.type       = Image.Type.Filled;
            suspFillImg.fillMethod = Image.FillMethod.Vertical;
            suspFillImg.fillOrigin = (int)Image.OriginVertical.Bottom;
            suspFillImg.fillAmount = 0f;
            var suspFillRect = suspFillGo.GetComponent<RectTransform>();
            suspFillRect.anchorMin = new Vector2(0f, 0f);
            suspFillRect.anchorMax = new Vector2(1f, 0.87f);
            suspFillRect.offsetMin = new Vector2(4f, 4f);
            suspFillRect.offsetMax = new Vector2(-4f, 0f);

            // ── Judgment Popup Text ───────────────────────────────────────────
            var popupGo   = new GameObject("PopupText");
            popupGo.transform.SetParent(canvasGo.transform, false);
            var popupText = popupGo.AddComponent<Text>();
            popupText.text      = "Perfect!";
            popupText.fontSize  = 72;
            popupText.fontStyle = FontStyle.Bold;
            popupText.alignment = TextAnchor.MiddleCenter;
            popupText.color     = Color.white;
            popupText.resizeTextForBestFit = false;
            var popupRect = popupGo.GetComponent<RectTransform>();
            popupRect.anchorMin = new Vector2(0.25f, 0.55f);
            popupRect.anchorMax = new Vector2(0.75f, 0.72f);
            popupRect.offsetMin = Vector2.zero;
            popupRect.offsetMax = Vector2.zero;
            popupGo.SetActive(false);

            // Judgment timing hint (早了 / 晚了)
            var hintGo   = new GameObject("JudgmentHint");
            hintGo.transform.SetParent(canvasGo.transform, false);
            var hintText = hintGo.AddComponent<Text>();
            hintText.text      = "← 早了";
            hintText.fontSize  = 28;
            hintText.alignment = TextAnchor.MiddleCenter;
            hintText.color     = Color.white;
            var hintRect = hintGo.GetComponent<RectTransform>();
            hintRect.anchorMin = new Vector2(0.25f, 0.50f);
            hintRect.anchorMax = new Vector2(0.75f, 0.57f);
            hintRect.offsetMin = Vector2.zero;
            hintRect.offsetMax = Vector2.zero;
            hintGo.SetActive(false);

            // ── Score / Combo / Time bar (top) ────────────────────────────────
            // Time (top left)
            var timeGo   = new GameObject("TimeText");
            timeGo.transform.SetParent(canvasGo.transform, false);
            var timeText = timeGo.AddComponent<Text>();
            timeText.text      = "0:00";
            timeText.fontSize  = 28;
            timeText.alignment = TextAnchor.MiddleLeft;
            timeText.color     = Color.white;
            var timeRect = timeGo.GetComponent<RectTransform>();
            timeRect.anchorMin = new Vector2(0.10f, 0.92f);
            timeRect.anchorMax = new Vector2(0.30f, 1.00f);
            timeRect.offsetMin = Vector2.zero;
            timeRect.offsetMax = Vector2.zero;

            // Score (top center)
            var scoreGo   = new GameObject("ScoreText");
            scoreGo.transform.SetParent(canvasGo.transform, false);
            var scoreText = scoreGo.AddComponent<Text>();
            scoreText.text      = "Score: 0";
            scoreText.fontSize  = 30;
            scoreText.fontStyle = FontStyle.Bold;
            scoreText.alignment = TextAnchor.MiddleCenter;
            scoreText.color     = Color.white;
            var scoreRect = scoreGo.GetComponent<RectTransform>();
            scoreRect.anchorMin = new Vector2(0.35f, 0.92f);
            scoreRect.anchorMax = new Vector2(0.65f, 1.00f);
            scoreRect.offsetMin = Vector2.zero;
            scoreRect.offsetMax = Vector2.zero;

            // Combo (top right-center)
            var comboGo   = new GameObject("ComboText");
            comboGo.transform.SetParent(canvasGo.transform, false);
            var comboText = comboGo.AddComponent<Text>();
            comboText.text      = "";
            comboText.fontSize  = 28;
            comboText.fontStyle = FontStyle.Bold;
            comboText.alignment = TextAnchor.MiddleRight;
            comboText.color     = new Color(1f, 0.9f, 0.2f, 1f);
            var comboRect = comboGo.GetComponent<RectTransform>();
            comboRect.anchorMin = new Vector2(0.65f, 0.92f);
            comboRect.anchorMax = new Vector2(0.88f, 1.00f);
            comboRect.offsetMin = Vector2.zero;
            comboRect.offsetMax = Vector2.zero;

            // ── Results Panel (hidden) ────────────────────────────────────────
            var resultsPanelGo = new GameObject("ResultsPanel");
            resultsPanelGo.transform.SetParent(canvasGo.transform, false);
            var resultsBg = resultsPanelGo.AddComponent<Image>();
            resultsBg.color = new Color(0f, 0f, 0f, 0.85f);
            var resultsPanelRect = resultsPanelGo.GetComponent<RectTransform>();
            resultsPanelRect.anchorMin = new Vector2(0.25f, 0.20f);
            resultsPanelRect.anchorMax = new Vector2(0.75f, 0.85f);
            resultsPanelRect.offsetMin = Vector2.zero;
            resultsPanelRect.offsetMax = Vector2.zero;

            var resultsTitleGo   = new GameObject("ResultsTitle");
            resultsTitleGo.transform.SetParent(resultsPanelGo.transform, false);
            var resultsTitleText = resultsTitleGo.AddComponent<Text>();
            resultsTitleText.text      = "演出完成！";
            resultsTitleText.fontSize  = 48;
            resultsTitleText.fontStyle = FontStyle.Bold;
            resultsTitleText.alignment = TextAnchor.MiddleCenter;
            resultsTitleText.color     = Color.yellow;
            var resultsTitleRect = resultsTitleGo.GetComponent<RectTransform>();
            resultsTitleRect.anchorMin = new Vector2(0f, 0.72f);
            resultsTitleRect.anchorMax = new Vector2(1f, 1.00f);
            resultsTitleRect.offsetMin = Vector2.zero;
            resultsTitleRect.offsetMax = Vector2.zero;

            var resultsBodyGo   = new GameObject("ResultsBody");
            resultsBodyGo.transform.SetParent(resultsPanelGo.transform, false);
            var resultsBodyText = resultsBodyGo.AddComponent<Text>();
            resultsBodyText.text      = "";
            resultsBodyText.fontSize  = 26;
            resultsBodyText.alignment = TextAnchor.MiddleCenter;
            resultsBodyText.color     = Color.white;
            var resultsBodyRect = resultsBodyGo.GetComponent<RectTransform>();
            resultsBodyRect.anchorMin = new Vector2(0.05f, 0f);
            resultsBodyRect.anchorMax = new Vector2(0.95f, 0.70f);
            resultsBodyRect.offsetMin = Vector2.zero;
            resultsBodyRect.offsetMax = Vector2.zero;

            resultsPanelGo.SetActive(false);

            // ── Pause Overlay (hidden) ────────────────────────────────────────
            var pausePanelGo = new GameObject("PausePanel");
            pausePanelGo.transform.SetParent(canvasGo.transform, false);
            var pauseBg = pausePanelGo.AddComponent<Image>();
            pauseBg.color = new Color(0f, 0f, 0f, 0.65f);
            FillParent(pausePanelGo.GetComponent<RectTransform>());

            var pauseTextGo   = new GameObject("PauseText");
            pauseTextGo.transform.SetParent(pausePanelGo.transform, false);
            var pauseText = pauseTextGo.AddComponent<Text>();
            pauseText.text      = "PAUSED";
            pauseText.fontSize  = 48;
            pauseText.alignment = TextAnchor.MiddleCenter;
            pauseText.color     = Color.white;
            var pauseTextRect = pauseTextGo.GetComponent<RectTransform>();
            pauseTextRect.anchorMin = new Vector2(0.3f, 0.4f);
            pauseTextRect.anchorMax = new Vector2(0.7f, 0.65f);
            pauseTextRect.offsetMin = Vector2.zero;
            pauseTextRect.offsetMax = Vector2.zero;

            pausePanelGo.SetActive(false);

            // ── EventSystem ──────────────────────────────────────────────────
            // Project uses New Input System package — use InputSystemUIInputModule,
            // not the legacy StandaloneInputModule.
            var evtGo = new GameObject("EventSystem");
            evtGo.AddComponent<UnityEngine.EventSystems.EventSystem>();
            evtGo.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();

            // ── Game Systems ─────────────────────────────────────────────────
            var systemsGo = new GameObject("GameSystems");

            var bmlGo  = new GameObject("BeatMapLoader");
            bmlGo.transform.SetParent(systemsGo.transform);
            var beatMapLoader = bmlGo.AddComponent<BeatMapLoader>();

            var isGo  = new GameObject("InputSystem");
            isGo.transform.SetParent(systemsGo.transform);
            var inputSystem = isGo.AddComponent<InputSystem>();

            var amGo  = new GameObject("AudioManager");
            amGo.transform.SetParent(systemsGo.transform);
            var audioManager = amGo.AddComponent<AudioManager>();

            var tjGo  = new GameObject("TimingJudgment");
            tjGo.transform.SetParent(systemsGo.transform);
            var timingJudgment = tjGo.AddComponent<TimingJudgment>();

            var bgaugGo = new GameObject("BloatGauge");
            bgaugGo.transform.SetParent(systemsGo.transform);
            var bloatGauge = bgaugGo.AddComponent<BloatGauge>();

            var smGo  = new GameObject("SuspicionMeter");
            smGo.transform.SetParent(systemsGo.transform);
            var suspicionMeter = smGo.AddComponent<SuspicionMeter>();

            var sarGo = new GameObject("ScoreAndRating");
            sarGo.transform.SetParent(systemsGo.transform);
            var scoreAndRating = sarGo.AddComponent<ScoreAndRating>();

            // VisualCueSystem and GameHUD both live on the Canvas root
            var visualCueSystem = canvasGo.AddComponent<VisualCueSystem>();
            var gameHUD         = canvasGo.AddComponent<GameHUD>();

            var lfmGo = new GameObject("LevelFlowManager");
            var lfm   = lfmGo.AddComponent<LevelFlowManager>();

            // ── Wire VisualCueSystem ──────────────────────────────────────────
            var vcsSO = new SerializedObject(visualCueSystem);
            vcsSO.FindProperty("_trackRect")     .objectReferenceValue = trackRect;
            vcsSO.FindProperty("_notePrefab")    .objectReferenceValue = notePrefabGo;
            vcsSO.FindProperty("_popupText")     .objectReferenceValue = popupText;
            vcsSO.FindProperty("_bloatFillImage")     .objectReferenceValue = bloatFillImg;
            vcsSO.FindProperty("_suspicionFillImage") .objectReferenceValue = suspFillImg;
            vcsSO.FindProperty("_vignetteImage")      .objectReferenceValue = vigImg;
            vcsSO.FindProperty("_timingJudgment").objectReferenceValue = timingJudgment;
            vcsSO.FindProperty("_bloatGauge")    .objectReferenceValue = bloatGauge;
            vcsSO.FindProperty("_suspicionMeter").objectReferenceValue = suspicionMeter;
            vcsSO.FindProperty("_beatMapLoader") .objectReferenceValue = beatMapLoader;
            vcsSO.FindProperty("_audioManager")  .objectReferenceValue = audioManager;
            vcsSO.ApplyModifiedProperties();

            // ── Wire LevelFlowManager ─────────────────────────────────────────
            var lfmSO = new SerializedObject(lfm);
            lfmSO.FindProperty("_beatMapLoader")  .objectReferenceValue = beatMapLoader;
            lfmSO.FindProperty("_audioManager")   .objectReferenceValue = audioManager;
            lfmSO.FindProperty("_inputSystem")    .objectReferenceValue = inputSystem;
            lfmSO.FindProperty("_timingJudgment") .objectReferenceValue = timingJudgment;
            lfmSO.FindProperty("_bloatGauge")     .objectReferenceValue = bloatGauge;
            lfmSO.FindProperty("_suspicionMeter") .objectReferenceValue = suspicionMeter;
            lfmSO.FindProperty("_scoreAndRating") .objectReferenceValue = scoreAndRating;
            lfmSO.FindProperty("_visualCueSystem").objectReferenceValue = visualCueSystem;
            lfmSO.ApplyModifiedProperties();

            // ── Wire GameHUD ──────────────────────────────────────────────────
            var hudSO = new SerializedObject(gameHUD);
            hudSO.FindProperty("_scoreText")        .objectReferenceValue = scoreText;
            hudSO.FindProperty("_comboText")        .objectReferenceValue = comboText;
            hudSO.FindProperty("_timeText")         .objectReferenceValue = timeText;
            hudSO.FindProperty("_judgmentHintText") .objectReferenceValue = hintText;
            hudSO.FindProperty("_resultsPanel")     .objectReferenceValue = resultsPanelGo;
            hudSO.FindProperty("_resultsTitleText") .objectReferenceValue = resultsTitleText;
            hudSO.FindProperty("_resultsBodyText")  .objectReferenceValue = resultsBodyText;
            hudSO.FindProperty("_pausePanel")       .objectReferenceValue = pausePanelGo;
            hudSO.FindProperty("_pauseText")        .objectReferenceValue = pauseText;
            hudSO.FindProperty("_timingJudgment")   .objectReferenceValue = timingJudgment;
            hudSO.FindProperty("_scoreAndRating")   .objectReferenceValue = scoreAndRating;
            hudSO.FindProperty("_audioManager")     .objectReferenceValue = audioManager;
            hudSO.FindProperty("_levelFlowManager") .objectReferenceValue = lfm;
            hudSO.ApplyModifiedProperties();

            // ── Wire TimingJudgment ───────────────────────────────────────────
            var tjSO = new SerializedObject(timingJudgment);
            tjSO.FindProperty("_inputSystem").objectReferenceValue = inputSystem;
            tjSO.ApplyModifiedProperties();

            // ── Save scene ────────────────────────────────────────────────────
            EditorSceneManager.SaveScene(scene, "Assets/Scenes/Sprint2Dev.unity");
            AssetDatabase.Refresh();

            Debug.Log("[Sprint2SceneBuilder] Done! Scene saved to Assets/Scenes/Sprint2Dev.unity");
        }

        // ── Helpers ───────────────────────────────────────────────────────────

        /// <summary>Returns production path if the file exists on disk, else placeholder.</summary>
        private static string Pick(string production, string placeholder)
        {
            // AssetDatabase path → absolute path
            string abs = System.IO.Path.Combine(
                Application.dataPath.Replace("Assets", ""),
                production.Replace('/', System.IO.Path.DirectorySeparatorChar));
            bool exists = System.IO.File.Exists(abs);
            if (!exists)
                Debug.Log($"[Sprint2SceneBuilder] Using placeholder for: {production}");
            return exists ? production : placeholder;
        }

        private static void SetSprite(string path)
        {
            var importer = AssetImporter.GetAtPath(path) as TextureImporter;
            if (importer == null)
            {
                Debug.LogWarning($"[Sprint2SceneBuilder] TextureImporter not found: {path}");
                return;
            }

            bool dirty = false;
            if (importer.textureType != TextureImporterType.Sprite)
            {
                importer.textureType = TextureImporterType.Sprite;
                dirty = true;
            }
            // Ensure Single sprite mode so LoadAssetAtPath<Sprite> works
            if (importer.spriteImportMode != SpriteImportMode.Single)
            {
                importer.spriteImportMode = SpriteImportMode.Single;
                dirty = true;
            }
            if (dirty)
            {
                EditorUtility.SetDirty(importer);
                importer.SaveAndReimport();
            }
        }

        private static Sprite LoadSprite(string path)
        {
            // Try direct load (Single sprite mode)
            var s = AssetDatabase.LoadAssetAtPath<Sprite>(path);
            if (s != null) return s;

            // Fallback: scan all sub-assets (Multiple sprite mode)
            foreach (var obj in AssetDatabase.LoadAllAssetsAtPath(path))
                if (obj is Sprite sp) return sp;

            Debug.LogWarning($"[Sprint2SceneBuilder] Sprite not found at: {path}");
            return null;
        }

        private static T Load<T>(string path) where T : Object
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset == null)
                Debug.LogWarning($"[Sprint2SceneBuilder] Asset not found at: {path}");
            return asset;
        }

        private static GameObject CreateImage(Transform parent, string name, Sprite sprite)
        {
            var go  = new GameObject(name);
            go.transform.SetParent(parent, false);
            var img = go.AddComponent<Image>();
            if (sprite != null) img.sprite = sprite;
            return go;
        }

        private static void FillParent(RectTransform rt)
        {
            rt.anchorMin = Vector2.zero;
            rt.anchorMax = Vector2.one;
            rt.offsetMin = Vector2.zero;
            rt.offsetMax = Vector2.zero;
        }
    }
}
